"""The CLI surface documents itself, or the suite fails.

`nat2 help` is generated by walking the Typer app, not maintained by hand, so
it cannot drift out of date. These tests are what make that guarantee real: a
command added without a docstring, or with a summary too long to be a one-liner,
breaks the build rather than quietly shipping an undocumented capability.
"""

from __future__ import annotations

import pytest
from typer.testing import CliRunner

from nat2.cli import app, command_summaries

runner = CliRunner()

MAX_SUMMARY_CHARS = 90


def test_there_are_commands_to_document():
    assert len(command_summaries()) > 10


@pytest.mark.parametrize("path,summary", command_summaries())
def test_every_command_has_a_one_line_summary(path, summary):
    assert summary, f"`nat2 {path}` has no docstring, so `nat2 help` cannot describe it"
    assert "\n" not in summary
    assert len(summary) <= MAX_SUMMARY_CHARS, (
        f"`nat2 {path}` summary is {len(summary)} chars; keep the first docstring "
        f"line under {MAX_SUMMARY_CHARS} so `nat2 help` stays scannable"
    )
    assert summary[0].isupper() or summary[0] in "`", f"`nat2 {path}` summary looks unfinished"


@pytest.mark.parametrize("path,_summary", command_summaries())
def test_every_command_responds_to_help(path, _summary):
    result = runner.invoke(app, path.split() + ["--help"])
    assert result.exit_code == 0, f"`nat2 {path} --help` exited {result.exit_code}"


def test_help_lists_every_command():
    result = runner.invoke(app, ["help"])
    assert result.exit_code == 0
    # Rich may wrap the summary text, but the command path itself must appear.
    for path, _ in command_summaries():
        assert path in result.output, f"`nat2 help` does not mention `{path}`"


def test_help_paths_is_machine_readable():
    # test.sh drives its smoke pass off this, so it must stay bare.
    result = runner.invoke(app, ["help", "--paths"])
    assert result.exit_code == 0
    lines = [line for line in result.output.splitlines() if line.strip()]
    assert sorted(lines) == sorted(path for path, _ in command_summaries())
    assert all(not line.startswith(" ") for line in lines)


def test_bare_invocation_shows_help_rather_than_doing_anything():
    result = runner.invoke(app, [])
    assert result.exit_code != 0 or "Usage" in result.output


def test_unknown_stream_is_rejected_with_the_known_list():
    result = runner.invoke(app, ["audit", "feed", "--streams", "hl.nonsense"])
    assert result.exit_code != 0
    assert "hl.trades" in result.output


def test_gate_names_in_status_match_the_designed_gates():
    from nat2.cli import gate_status  # noqa: F401

    result = runner.invoke(app, ["gate", "status", "--ledger", "/nonexistent/l.jsonl"])
    assert result.exit_code == 0
    for gate in ("feed", "map", "magnet", "persistence", "decay"):
        assert gate in result.output
